---
# https://wiki.winehq.org/Download
# https://en.opensuse.org/Wine#Repositories

# https://wiki.winehq.org/Debian
# https://wiki.winehq.org/Ubuntu
# https://stackoverflow.com/a/33377943/5430535
- name: Add amd64 and i386 arch 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  lineinfile:
    dest: /var/lib/dpkg/arch
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - amd64
    - i386

#--- Ubuntu 18.04\bionic, Debian 10 ---#

# https://askubuntu.com/a/1205535

- name: Get info about enabled repo components (contrib)
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  shell: grep -v '#' /etc/apt/sources.list | grep -v src | grep contrib
  register: etc_apt_sources_list
  ignore_errors: yes
  changed_when: false

- name: Set fact about part of OBS deb repo
  block:
    - set_fact:
        wine_obs_distro_name_fact: Debian
        wine_obs_distro_version_fact: "{{ ansible_distribution_major_version }}"
      when: ansible_distribution == 'Debian'
    - set_fact:
        wine_obs_distro_name_fact: xUbuntu
        wine_obs_distro_version_fact: "{{ ansible_distribution_version }}"
      when: ansible_distribution == 'Ubuntu'

- name: Add Wine OBS repo key 4 Ubuntu 18.04
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - (ansible_distribution == 'Debian')
      or
      (ansible_distribution == 'Ubuntu')
    - (ansible_distribution_release == 'buster')
      or
      (ansible_distribution_release == 'bionic')
  become: yes
  vars:
    wine_obs_repo_deb_key: https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/{{ wine_obs_distro_name_fact }}_{{ wine_obs_distro_version_fact }}/Release.key
  apt_key:
    url: "{{ wine_obs_repo_deb_key }}"
    state: present

- name: Config dependences config file 4 Ubuntu 18.04, Debian 10
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - (ansible_distribution == 'Debian')
      or
      (ansible_distribution == 'Ubuntu')
    - (ansible_distribution_release == 'buster')
      or
      (ansible_distribution_release == 'bionic')
  become: yes
  copy:
    dest: /etc/apt/preferences.d/dependences-4-wine
    mode: 644
    content: |
      # https://askubuntu.com/a/1205535
      Package: libfaudio0
      Pin: release n={{ ansible_distribution_release }}
      Pin-Priority: 500

- name: Add Wine repo OBS 4 Ubuntu 18.04, Debian 10
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - (ansible_distribution == 'Debian')
      or
      (ansible_distribution == 'Ubuntu')
    - (ansible_distribution_release == 'buster')
      or
      (ansible_distribution_release == 'bionic')
  become: yes
  apt_repository:
    repo:
      'deb
      {{ http_or_https }}://download.opensuse.org/repositories/Emulators:/Wine:/Debian/{{ wine_obs_distro_name_fact }}_{{ wine_obs_distro_version_fact }}/ /'
    state: present
    filename: wine-obs

# https://www.linux.org.ru/forum/general/14131012?cid=14131586
- name: Add contrib component 4 Debian 10
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'
    # - wine_install_winetricks == true
    - wine_install_winetricks
    - etc_apt_sources_list.rc == 1
  become: yes
  apt_repository:
    repo: deb {{ http_or_https }}://deb.debian.org/debian {{ ansible_distribution_release }} contrib
    state: present

#--------------------#

- name: Add Wine repo key 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  apt_key:
    url: "{{ wine_repo_deb_key }}"
    state: present

- name: Add Wine repo 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  apt_repository:
    repo:
      'deb
      {{ http_or_https }}://dl.winehq.org/wine-builds/{{ ansible_lsb.id | lower }}/
      {{ ansible_distribution_release }}
      main'
    state: present
    filename: wine

#---

# https://wiki.winehq.org/Fedora
# https://dl.winehq.org/wine-builds/fedora/34/winehq.repo
- name: Add repo Wine 4 Fedora
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
    - ansible_distribution == 'Fedora'
  become: yes
  yum_repository:
    file: wine
    name: WineHQ
    description: WineHQ packages
    baseurl: '{{ http_or_https }}://dl.winehq.org/{{ ansible_lsb.id | lower }}/{{ ansible_distribution_major_version }}'
    gpgkey: '{{ wine_repo_rpm_key }}'
    enabled: yes
    gpgcheck: yes
    state: present

#---

# https://download.opensuse.org/repositories/Emulators:/Wine/openSUSE_Leap_15.3/Emulators:Wine.repo
- name: Add repo Wine 4 {{ ansible_distribution }}
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Leap'
  become: yes
  zypper_repository:
    name: Wine ({{ ansible_distribution }})
    repo:
      "{{ http_or_https }}://download.opensuse.org/repositories/Emulators:/Wine/{{ ansible_distribution | replace(' ', '_') }}_{{ ansible_lsb.release }}/"
    state: present
    auto_import_keys: yes
    runrefresh: yes
    autorefresh: yes

# https://download.opensuse.org/repositories/Emulators:/Wine/openSUSE_Tumbleweed/Emulators:Wine.repo
- name: Add repo Wine 4 {{ ansible_distribution }}
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Tumbleweed'
  become: yes
  zypper_repository:
    name: Wine ({{ ansible_distribution }})
    repo:
      "{{ http_or_https }}://download.opensuse.org/repositories/Emulators:/Wine/{{ ansible_distribution | replace(' ', '_') }}/"
    state: present
    auto_import_keys: yes
    runrefresh: yes
    autorefresh: yes
