---
# https://wiki.winehq.org/Download
# https://en.opensuse.org/Wine#Repositories

# https://wiki.winehq.org/Ubuntu
# https://wiki.winehq.org/Debian
- name: Add wine repo key 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  apt_key:
    url: "{{ wine_repo_deb_key }}"
    state: present

- name: Add wine repo 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  apt_repository:
    repo:
      'deb [arch=amd64]
      {{ http_or_https }}://dl.winehq.org/wine-builds/{{ ansible_lsb.id | lower }}/
      {{ ansible_distribution_release }}
      main'
    state: present
    filename: wine

#---

# https://wiki.winehq.org/CentOS/RHEL
- name: Add EPEL repo 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
    - ansible_distribution != 'Fedora'
  become: yes
  package:
    name:
      - epel-release
    state: present

# https://wiki.winehq.org/Fedora
# https://dl.winehq.org/wine-builds/fedora/34/winehq.repo
- name: Add repo wine 4 Fedora
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
    - ansible_distribution != 'CentOS'
  become: yes
  yum_repository:
    file: wine
    name: WineHQ
    description: WineHQ packages
    baseurl: '{{ http_or_https }}://dl.winehq.org/{{ ansible_lsb.id | lower }}/{{ ansible_distribution_major_version }}'
    gpgkey: '{{ wine_repo_rpm_key }}'
    enabled: yes
    gpgcheck: yes
    state: present

#---

# https://download.opensuse.org/repositories/Emulators:/Wine/openSUSE_Leap_15.3/Emulators:Wine.repo
- name: Add repo wine 4 {{ ansible_distribution }}
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Leap'
  become: yes
  zypper_repository:
    name: Wine ({{ ansible_distribution }})
    repo:
      "{{ http_or_https }}://download.opensuse.org/repositories/Emulators:/Wine/{{ ansible_distribution | replace(' ', '_') }}_{{ ansible_lsb.release }}/"
    state: present
    auto_import_keys: yes
    runrefresh: yes
    autorefresh: yes

# https://download.opensuse.org/repositories/Emulators:/Wine/openSUSE_Tumbleweed/Emulators:Wine.repo
- name: Add repo wine 4 {{ ansible_distribution }}
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Tumbleweed'
  become: yes
  zypper_repository:
    name: Wine ({{ ansible_distribution }})
    repo:
      "{{ http_or_https }}://download.opensuse.org/repositories/Emulators:/Wine/{{ ansible_distribution | replace(' ', '_') }}/"
    state: present
    auto_import_keys: yes
    runrefresh: yes
    autorefresh: yes
